"""
review_processor.py - Read and process a CA-reviewed exception report.

The CA opens the Excel file generated by report_writer.py, fills in
"CA Review Status" and optionally "CA Remarks" for each row, then saves
the file. This module reads the annotated file back and produces a
filing recommendation summary.
"""

from pathlib import Path

import pandas as pd

ALLOWED_REVIEW_STATUSES = {"Accepted", "Escalated", "Pending", "Hold ITC", "Reverse ITC"}

REQUIRED_REVIEW_COLUMNS = [
    "Invoice No",
    "Supplier GSTIN",
    "ITC At Risk",
    "CA Review Status",
    "CA Remarks",
]


def load_reviewed_report(file_path):
    """
    Load a CA-reviewed Excel report and return it as a DataFrame.

    Raises:
        FileNotFoundError: if the file does not exist
        ValueError: if the file contains no rows
    """
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"Reviewed report not found: {path}")

    df = pd.read_excel(path, engine="openpyxl")

    if df.empty:
        raise ValueError(f"Reviewed report is empty: {path}")

    return df


def validate_review_columns(df):
    """
    Check that the reviewed report contains the required columns.

    Raises:
        ValueError: listing every missing column name
    """
    missing = set(REQUIRED_REVIEW_COLUMNS) - set(df.columns)
    if missing:
        raise ValueError(f"Missing columns in reviewed report: {sorted(missing)}")
    return True


def normalize_review_status(value):
    """
    Normalize a CA Review Status value to a canonical form.

    - Blank or null → "Pending"
    - Case-insensitive match against allowed statuses
    - Unrecognised values are returned cleaned (validate_review_statuses catches them)
    """
    if pd.isna(value) or str(value).strip() == "":
        return "Pending"

    cleaned = str(value).strip()
    lower = cleaned.lower()

    if lower == "accepted":
        return "Accepted"
    if lower == "escalated":
        return "Escalated"
    if lower == "pending":
        return "Pending"
    if lower == "hold itc":
        return "Hold ITC"
    if lower == "reverse itc":
        return "Reverse ITC"

    return cleaned


def validate_review_statuses(df):
    """
    Normalize all CA Review Status values and check they are all allowed.

    Returns a copy of df with the "CA Review Status" column normalized.

    Raises:
        ValueError: listing the invalid values found
    """
    df_copy = df.copy()
    df_copy["CA Review Status"] = df_copy["CA Review Status"].apply(normalize_review_status)

    invalid = set(df_copy["CA Review Status"]) - ALLOWED_REVIEW_STATUSES
    if invalid:
        raise ValueError(f"Invalid CA Review Status values: {sorted(invalid)}")

    return df_copy


def calculate_review_summary(df):
    """
    Compute counts and ITC amounts grouped by CA Review Status.

    Returns a dict with counts per status and rupee totals.
    """
    itc_col = df["ITC At Risk"].apply(lambda x: float(x) if pd.notna(x) else 0.0)

    status = df["CA Review Status"]

    return {
        "total_exception_rows": len(df),
        "accepted_count": int((status == "Accepted").sum()),
        "escalated_count": int((status == "Escalated").sum()),
        "pending_count": int((status == "Pending").sum()),
        "hold_itc_count": int((status == "Hold ITC").sum()),
        "reverse_itc_count": int((status == "Reverse ITC").sum()),
        "total_itc_at_risk": float(itc_col.sum()),
        "accepted_itc": float(itc_col[status == "Accepted"].sum()),
        "hold_itc": float(itc_col[status == "Hold ITC"].sum()),
        "reverse_itc": float(itc_col[status == "Reverse ITC"].sum()),
        "unresolved_itc": float(itc_col[status.isin(["Escalated", "Pending"])].sum()),
    }


def get_filing_recommendation(summary):
    """
    Return a one-line filing recommendation based on the review summary.

    Priority order: unresolved items block filing before ITC adjustments,
    which in turn precede a clean all-accepted result.
    """
    if summary["pending_count"] > 0 or summary["escalated_count"] > 0:
        return "Do not finalize filing until pending/escalated items are reviewed."

    if summary["hold_itc_count"] > 0 or summary["reverse_itc_count"] > 0:
        return "File only after adjusting held/reversed ITC."

    if summary["accepted_count"] == summary["total_exception_rows"]:
        return "Filing position appears reviewed and ready."

    return "Review required."


def print_review_summary(summary):
    """
    Print a formatted CA review summary to stdout.
    """
    print("CA Review Summary:")
    print(f"  Total exception rows: {summary['total_exception_rows']}")
    print(f"  Accepted: {summary['accepted_count']}")
    print(f"  Escalated: {summary['escalated_count']}")
    print(f"  Pending: {summary['pending_count']}")
    print(f"  Hold ITC: {summary['hold_itc_count']}")
    print(f"  Reverse ITC: {summary['reverse_itc_count']}")
    print()
    print("ITC Position:")
    print(f"  Total ITC at Risk: ₹{summary['total_itc_at_risk']:,.2f}")
    print(f"  Accepted ITC: ₹{summary['accepted_itc']:,.2f}")
    print(f"  Hold ITC: ₹{summary['hold_itc']:,.2f}")
    print(f"  Reverse ITC: ₹{summary['reverse_itc']:,.2f}")
    print(f"  Unresolved ITC: ₹{summary['unresolved_itc']:,.2f}")
    print()
    print("Recommendation:")
    print(f"  {summary['filing_recommendation']}")


def process_reviewed_report(file_path):
    """
    Orchestrate the full review processing pipeline.

    Steps:
      1. Load the reviewed Excel file
      2. Validate required columns exist
      3. Normalize and validate CA Review Status values
      4. Compute summary counts and ITC amounts
      5. Derive a filing recommendation

    Returns:
        dict with all summary fields including "filing_recommendation"
    """
    df = load_reviewed_report(file_path)
    validate_review_columns(df)
    df = validate_review_statuses(df)
    summary = calculate_review_summary(df)
    summary["filing_recommendation"] = get_filing_recommendation(summary)
    return summary
